[package]
name = "ipscoreboard"
version = "0.1.0"
authors = ["neelay"]

[dependencies]
iron = "0.6.*"
hyper = "0.10.*"
rusqlite = "0.16.0"
curl = "0.4.19"
serde_json = "1.0.37"
serde = "1.0.60"
serde_derive = "1.0"
